[package]
name = "gitui"
version = "0.1.0"
authors = ["Stephan Dilly <dilly.stephan@gmail.com>"]
description = "blazing fast terminal-ui for git"
license = "MIT"
homepage = "https://gitui.org"
edition = "2018"

[dependencies]
git2 = "0.10"
crossterm = "0.15"
itertools = "0.9"
log = "0.4"
simplelog = "0.7"
dirs = "2.0"
tui = { version = "0.8", default-features = false, features = ['crossterm'] }