[package]
name = "gitui"
version = "0.1.1"
authors = ["Stephan Dilly <dilly.stephan@gmail.com>"]
description = "blazing fast terminal-ui for git"
edition = "2018"
exclude = ["assets/*"]
homepage = "https://gitui.org"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]
keywords = [
	"git",
    "gui",
	"cli",
	"terminal",
    "ui",
	"text",
	"linux",
    "windows",
    "macos",
    "binary",
]

[dependencies]
crossterm = "0.15"
tui = { version = "0.8", default-features=false, features = ['crossterm'] }
itertools = "0.9"
log = "0.4"
simplelog = "0.7"
dirs = "2.0"
crossbeam-channel = "0.4"
scopetime = { path = "./scopetime", version = "0.1" }
asyncgit = { path = "./asyncgit", version = "0.1" }

[features]
default=[]
timing=["scopetime/enabled"]

[workspace]
members=[
    "asyncgit",
    "scopetime",
]