[package]
name = "gitterm"
version = "0.1.0"
authors = ["Stephan Dilly <dilly.stephan@gmail.com>"]
edition = "2018"

[dependencies]
git2 = "0.10"
crossterm = "0.15"
tui = { version = "0.8", default-features = false, features = ['crossterm'] }