[package]
name = "asyncgit"
version = "0.1.1"
authors = ["Stephan Dilly <dilly.stephan@gmail.com>"]
edition = "2018"
description = "allow using git2 in a asynchronous context"
homepage = "https://gitui.org"
readme = "README.md"
license = "MIT"
categories = ["concurrency","asynchronous"]

[dependencies]
git2 = "0.10"
rayon-core = "1.7"
crossbeam-channel = "0.4"
log = "0.4"
scopetime = { path = "../scopetime", version = "0.1" }

[dev-dependencies]
tempfile = "3.1"